version: "3.8"
services:
  service1:
    build: ./service1
    container_name: service1_container
    environment:
      - SERVICE_NAME=service1
      - PORT=8080
    ports:
      - "8081:8080"
    networks:
      - appnet

  service2:
    build: ./service2
    container_name: service2_container
    environment:
      - SERVICE_NAME=service2
      - PORT=8080
    ports:
      - "8082:8080"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge