services:
  service1:
    build: ./service1
    container_name: service1_container
    environment:
      - SERVICE_NAME=service1
      - PORT=8080
    ports:
      - "8081:8080"
    networks:
      - appnet

  service2:
    build: ./service2
    container_name: service2_container
    environment:
      - SERVICE_NAME=service2
      - PORT=8080
    ports:
      - "8082:8080"
    networks:
      - appnet

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_container
    # Монтируем локальную конфигурацию nginx (чтобы использовать наш nginx/nginx.conf)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # Пробросим 80 контейнера на 8080 хоста — удобно для теста через nginx
    ports:
      - "8080:80"
    networks:
      - appnet
    depends_on:
      - service1
      - service2

networks:
  appnet:
    driver: bridge